const config = require("config");

module.exports.responseTimeTemp =
  '<tr><td style="padding: 5px" ><span>URL :</span><span>$url$</span></td></tr><tr><td style="padding: 5px" ><span>Response Time :</span><span>$responseTimeMilli$</span></td></tr>';
module.exports.fiveHundredErrorTemp =
  '<tr><td style="padding: 5px" ><span>URL :</span><span>$url$</span></td></tr><tr><td style="padding: 5px" ><span>Count :</span><span>$count$</span></td></tr>';
module.exports.sendLogEmail = `<!DOCTYPE html> <html> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;" /> <meta name="viewport" content="width=600,initial-scale = 2.3,user-scalable=no" /> <!--[if !mso]><!-- --> <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700" rel="stylesheet" /> <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,700" rel="stylesheet" /> <!-- <![endif]--> <title>Email</title> <style type="text/css"> body { width: 100%; background-color: #ffffff; margin: 0; padding: 0; -webkit-font-smoothing: antialiased; mso-margin-top-alt: 0px; mso-margin-bottom-alt: 0px; mso-padding-alt: 0px 0px 0px 0px; } p, h1, h2, h3, h4 { margin-top: 0; margin-bottom: 0; padding-top: 0; padding-bottom: 0; } span.preheader { display: none; font-size: 1px; } html { width: 100%; } table { font-size: 14px; border: 0; } } </style> <!-- [if gte mso 9]><style type=”text/css”> body { font-family: arial, sans-serif!important; } </style> <![endif]--> </head> 
<body class="respond" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"> <!-- header --> <table border="0" width="100%" cellpadding="0" cellspacing="0" bgcolor="ffffff"> <tr> <td align="center"> <table border="0" align="center" width="590" cellpadding="0" cellspacing="0" class="container590"> <tr> <td height="25" style="font-size: 25px; line-height: 25px">&nbsp;</td> </tr> <tr> <td align="center"> <table border="0" align="center" width="590" cellpadding="0" cellspacing="0" class="container590"> <tr> <td align="center" height="70" style="height: 70px"> <a href="" style="display: block; border-style: none !important; border: 0 !important" ><img width="300" border="0" style="display: block; width: 300px" src=${config.get(
  "logo"
)} alt="" /></a> </td> </tr> </table> </td> </tr> <tr> <td height="25" style="font-size: 25px; line-height: 25px">&nbsp;</td> </tr> <tr> <td align="center"> <table border="0" align="center" width="590" cellpadding="0" cellspacing="0" class="container590" style="border: 1px solid #eeeeee"><tr> <td style="color: #343434; font-size: 16px; font-family: Quicksand, Calibri, sans-serif; font-weight: 700; letter-spacing: 3px; line-height: 35px; padding: 5px" class="main-header" > <div style="line-height: 35px"><span>400 Error Count:</span><span>$errorCount$</span> </div></td> </tr> 
<tr> <td style="color: #343434; font-size: 16px; font-family: Quicksand, Calibri, sans-serif; font-weight: 700; letter-spacing: 3px; line-height: 35px; padding: 5px" class="main-header" > <div style="line-height: 35px">500 Error API Count : $totalFiveHundredError$</div> </td> </tr>$fiveHundredData$
<tr> <td style="color: #343434; font-size: 16px; font-family: Quicksand, Calibri, sans-serif; font-weight: 700; letter-spacing: 3px; line-height: 35px; padding: 5px" class="main-header" > <div style="line-height: 35px">Top 10 time consume api</div> </td> </tr>$data$
<tr> <td align="center"> <table border="0" width="40" align="center" cellpadding="0" cellspacing="0" bgcolor="eeeeee"> </table> </td> </tr> <tr> <td height="20" style="font-size: 20px; line-height: 20px">&nbsp;</td> </tr> <tr> <td align="center"> <table border="0" width="400" align="center" cellpadding="0" cellspacing="0" class="container590"> </table> </td> </tr> <tr> <td height="25" style="font-size: 25px; line-height: 25px">&nbsp;</td> </tr> <tr> <td align="center"> <table border="0" align="center" width="400" cellpadding="0" cellspacing="0" bgcolor="#96C809" style=""> </table> </td> </tr> <tr> <td height="30" style="font-size: 30px; line-height: 30px">&nbsp;</td> </tr> </table> </td> </tr> </table> </td> </tr> </table> <!-- end header --> </body> </html>`;

module.exports.sendFiveHundredLogEmail = `
<!DOCTYPE html> <html> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;" /> <meta name="viewport" content="width=600,initial-scale = 2.3,user-scalable=no" /> <!--[if !mso]><!-- --> <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700" rel="stylesheet" /> <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,700" rel="stylesheet" /> <!-- <![endif]--> <title>Email</title> <style type="text/css"> body { width: 100%; background-color: #ffffff; margin: 0; padding: 0; -webkit-font-smoothing: antialiased; mso-margin-top-alt: 0px; mso-margin-bottom-alt: 0px; mso-padding-alt: 0px 0px 0px 0px; } p, h1, h2, h3, h4 { margin-top: 0; margin-bottom: 0; padding-top: 0; padding-bottom: 0; } span.preheader { display: none; font-size: 1px; } html { width: 100%; } table { font-size: 14px; border: 0; } } </style> <!-- [if gte mso 9]><style type=”text/css”> body { font-family: arial, sans-serif!important; } </style> <![endif]--> </head> 
<body class="respond" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"> <!-- header --> <table border="0" width="100%" cellpadding="0" cellspacing="0" bgcolor="ffffff"> <tr> <td align="center"> <table border="0" align="center" width="590" cellpadding="0" cellspacing="0" class="container590"> <tr> <td height="25" style="font-size: 25px; line-height: 25px">&nbsp;</td> </tr> <tr> <td align="center"> <table border="0" align="center" width="590" cellpadding="0" cellspacing="0" class="container590"> <tr> <td align="center" height="70" style="height: 70px"> <a href="" style="display: block; border-style: none !important; border: 0 !important" ><img width="300" border="0" style="display: block; width: 300px" src=${config.get(
  "logo"
)} alt="" /></a> </td> </tr> </table> </td> </tr> <tr> <td height="25" style="font-size: 25px; line-height: 25px">&nbsp;</td> </tr> <tr> <td align="center"> <table border="0" align="center" width="590" cellpadding="0" cellspacing="0" class="container590" style="border: 1px solid #eeeeee"><tr> <td style="color: #343434; font-size: 16px; font-family: Quicksand, Calibri, sans-serif; font-weight: 700; letter-spacing: 3px; line-height: 35px; padding: 5px" class="main-header" > <div style="line-height: 35px"><span>400 Error Count:</span><span>$errorCount$</span> </div></td> </tr> 
<tr> <td style="color: #343434; font-size: 16px; font-family: Quicksand, Calibri, sans-serif; font-weight: 700; letter-spacing: 3px; line-height: 35px; padding: 5px" class="main-header" > <div style="line-height: 35px">500 Error API Count : $totalFiveHundredError$</div> </td> </tr>$fiveHundredData$
<tr> <td style="color: #343434; font-size: 16px; font-family: Quicksand, Calibri, sans-serif; font-weight: 700; letter-spacing: 3px; line-height: 35px; padding: 5px" class="main-header" > <div style="line-height: 35px">Top 10 time consume api</div> </td> </tr>$data$
<tr> <td align="center"> <table border="0" width="40" align="center" cellpadding="0" cellspacing="0" bgcolor="eeeeee"> </table> </td> </tr> <tr> <td height="20" style="font-size: 20px; line-height: 20px">&nbsp;</td> </tr> <tr> <td align="center"> <table border="0" width="400" align="center" cellpadding="0" cellspacing="0" class="container590"> </table> </td> </tr> <tr> <td height="25" style="font-size: 25px; line-height: 25px">&nbsp;</td> </tr> <tr> <td align="center"> <table border="0" align="center" width="400" cellpadding="0" cellspacing="0" bgcolor="#96C809" style=""> </table> </td> </tr> <tr> <td height="30" style="font-size: 30px; line-height: 30px">&nbsp;</td> </tr> </table> </td> </tr> </table> </td> </tr> </table> <!-- end header --> </body> </html>`;

module.exports.orderDetailsLog =
  '<tr><td style="padding: 5px" ><span>Cancelled Orders :</span><span>$cancelledOrders$</span></td></tr><tr><td style="padding: 5px" ><span>Driver Assigned:</span><span>$driverAssignedOrders$</span></td></tr><tr><td style="padding: 5px" ><span>Delivered Orders :</span><span>$deliveredOrders$</span></td></tr><tr><td style="padding: 5px" ><span>Returned Orders :</span><span>$returnedOrders$</span></td></tr><tr><td style="padding: 5px" ><span>Cod Orders :</span><span>$codOrders$</span></td></tr><tr><td style="padding: 5px" ><span>Online Orders  :</span><span>$onlineOrders$</span></td><tr><td style="padding: 5px" ><span>Payment Failure Orders :</span><span>$paymentFailureOrders$</span></td></tr><tr><td style="padding: 5px" ><span>Store Orders :</span><span>$storeOrders$</span></td></tr>';

module.exports.orderInvoice = `<!DOCTYPE html> <html> <head> <title>Page Title</title><style>.modal-body {line-height: 1.5;} table { border-collapse: collapse; width: 100%; margin-bottom: 5px;font-size: 10px; } th, td { text-align: left; padding: 8px; } tr:nth-child(even){background-color: #f2f2f2} th { background-color: #000; color: white; } .font { font-size: 10px } .w-100 { width: 100%; margin-bottom: 15px; font-size: 10px; }.wf-100 { width: 100%;font-size: 10px; } .w-30 { width: 30%; display: inline-block; } .w-70 { width: 68%;display: inline-block; color: #8c8e91;  } .wb-30 { width: 73%; display: inline-block; text-align: right; } .wb-70 { width: 25%;display: inline-block; text-align: right; } .align-right {text-align: right;} .rm { padding-right: 20px } .border-bottom {border-bottom: 1px solid #5c5d5e;} .footer { background: #cbc5c5; color: #077a11f2; padding-bottom: 5px; padding-top: 5px; } </style></head> <body> <div class="modal-body waive-share"> <div class="cat"> <h3 class="modal-title" id="modal-basic-title"> <span class="text-left">Waive: Summary and Receipt</span></h3> <div class="w-100"> <div class="w-30"> <div>Order ID: </div> <div>Order Time: </div> <div>Customer Name: </div> <div>Customer Address: </div> <div>Restaurant Name: </div> <div>Restaurant Address:</div> <div>Delivery partner's Name: </div> </div> <div class="w-70"> <div>$orderNo$</div> <div>$time$</div> <div>$customerName$</div> <div>$customerAddress$</div> <div>$restaurantName$</div> <div>$restaurantAddress$</div> <div>$driverName$</div> </div> </div> <div class="table-responsive"> <table class="table text-center border-bottom " id="table_app"> <thead> <tr class="t-heading"> <th class="align-middle">Item</th> <th class="align-right" >Quantity</th> <th class="align-right">Unit Price</th> <th class="align-right rm">Total Price</th> </tr> </thead> <tbody>$rows$</tbody> </table> <div class="w-100"> <div class="wb-30"> <div>Delivery Fees </div> <div>Vat Charges</div> <div>Service Tax</div> <div>Service Charges</div> <div>Discount</div> </div> <div class="wb-70"> <div>$deliveryFees$</div> <div>$vatCharges$</div> <div>$serviceTax$</div> <div>$serviceCharges$</div> <div>$discount$</div> </div><div class="wf-100 footer"> <div class="wb-30"> <div>Total</div> </div> <div class="wb-70"> <div>$totalPrice$</div> </div> </div></div> </div> </div> </body> </html>`;

module.exports.itemsRows = `<tr class="tr"> <td scope="col">$itemName$</td><td scope="col" class="align-right">$quantity$</td><td scope="col" class="align-right">$price$</td><td scope="col" class="align-right">$total$</td></tr>`;

module.exports.pickupAndDrop = `<!DOCTYPE html> <html> <head> <title>Page Title</title> <style> .modal-body {line-height: 1.5;} table { border-collapse: collapse; width: 100%; margin-bottom: 5px;font-size: 10px; } th, td { text-align: left; padding: 8px; }{background-color: #f2f2f2} th { background-color: #000; color: white; } .font { font-size: 10px } .w-100 { width: 100%; margin-bottom: 15px; font-size: 10px; }.wf-100 { width: 100%;font-size: 10px; } .w-30 { width: 30%; display: inline-block; } .w-70 { width: 68%;display: inline-block; color: #8c8e91;  } .wb-30 { width: 73%; display: inline-block; text-align: right; } .wb-70 { width: 25%;display: inline-block; text-align: right; } .align-right {text-align: right;} .rm { padding-right: 20px } .border-bottom {border-top: 1px solid #5c5d5e;padding-top: 5px;} .footer { background: #cbc5c5; color: #077a11f2; padding-bottom: 5px; padding-top: 5px; } .padding-0 { padding: 0px; } </style> </head> <body> <div class="modal-body waive-share"> <div class="cat"> <h3 class="modal-title" id="modal-basic-title"> <span class="text-left">Waive: Summary and Receipt</span></h3> <table> <tr> <td class="w-30 padding-0">Order ID:</td> <td class="w-70 padding-0">$orderNo$</td> </tr> <tr> <td class="w-30 padding-0">Order Time:</td> <td class="w-70 padding-0">$time$</td> </tr> <tr> <td class="w-30 padding-0">Recipient Name:</td> <td class="w-70 padding-0">$recipientName$</td> </tr> <tr> <td class="w-30 padding-0">Recipient Address:</td> <td class="w-70 padding-0">$recipientAddress$</td> </tr> <tr> <td class="w-30 padding-0">Sender Name:</td> <td class="w-70 padding-0">$senderName$</td> </tr> <tr> <td class="w-30 padding-0">Sender Address:</td> <td class="w-70 padding-0">$senderAddress$</td> </tr> <tr> <td class="w-30 padding-0">Delivery partner's Name:</td> <td class="w-70 padding-0">$driverName$</td> </tr> </table> <div class="table-responsive border-bottom"> <div class="w-100"> <div class="wb-30"> <div>Delivery Fare </div> <div>Ride Time Fare</div> <div>Waiting Time Fare</div> <div>Vat Charges</div> <div>Service Tax</div> <div>Discount</div> </div> <div class="wb-70"> <div>$deliveryFare$</div> <div>$rideTimeFare$</div> <div>$waitingTimefare$</div> <div>$vatCharges$</div> <div>$serviceTax$</div> <div>$discount$</div> </div> <div class="wf-100 footer"> <div class="wb-30"> <div>Total</div> </div> <div class="wb-70"> <div>$totalPrice$</div> </div> </div> </div> </div> </div> </body> </html>`;
