const express = require("express");
const reqLogger = require("../startup/logger");
const vendors = require("../routes/vendors");
const influencers = require("../routes/influencers");
const admins = require("../routes/admins");
const products = require("../routes/products");
const user = require("../routes/users");
const category = require("../routes/categories");
const unit = require("../routes/units");
const cart = require("../routes/carts");
const otp = require("../routes/otps");
const s3Upload = require("../routes/s3upload");
const storeManager = require("../routes/storeManagers");
const order = require("../routes/orders");
const auditLogs = require("../routes/auditLogs");
const cards = require("../routes/cards");
const address = require("../routes/addresses");
const webview = require("../routes/webviews");
const drivers = require("../routes/drivers");
const ratings = require("../routes/ratings");
const merchantCategories = require("../routes/merchantCategories");
const banners = require("../routes/banners");
const coupons = require("../routes/coupons");
const referrals = require("../routes/referrals");
const webhooks = require("../routes/webhooks");
const activities = require("../routes/activities");
const dashboard = require("../routes/dashboard");
const appVersions = require("../routes/appVersions");
const cities = require("../routes/cities");
const feeAndLimits = require("../routes/feeAndLimits");
const manualPayouts = require("../routes/manualPayouts");
const serviceAreas = require("../routes/serviceAreas");
const vehicleTypes = require("../routes/vehicleTypes");
const pickUpCategories = require("../routes/pickUpCategories");
const paymentHistories = require("../routes/paymentHistories");
const roles = require("../routes/roles");
const analysis = require("../routes/analysis");
const banks = require("../routes/banks");
const csvUpload = require("../routes/csvUpload");
// const webhooks = require("../routes/webhooks");

module.exports = function (app) {
  app.use(express.json({ limit: "500mb" }));
  app.use(reqLogger);
  app.use("/api/admin", admins);
  app.use("/api/vendor", vendors);
  app.use("/api/influencer", influencers);
  app.use("/api/product", products);
  app.use("/api/user", user);
  app.use("/api/category", category);
  app.use("/api/unit", unit);
  app.use("/api/cart", cart);
  app.use("/api/otp", otp);
  app.use("/api/s3upload", s3Upload);
  app.use("/api/storeManager", storeManager);
  app.use("/api/order", order);
  app.use("/api/auditLog", auditLogs);
  app.use("/api/card", cards);
  app.use("/api/address", address);
  app.use("/api/webview", webview);
  app.use("/api/drivers", drivers);
  app.use("/api/rating", ratings);
  app.use("/api/categoryBanner", merchantCategories);
  app.use("/api/banner", banners);
  app.use("/api/coupon", coupons);
  app.use("/api/referral", referrals);
  app.use("/api/webhook", webhooks);
  app.use("/api/activities", activities);
  app.use("/api/dashboard", dashboard);
  app.use("/api/version", appVersions);
  app.use("/api/city", cities);
  app.use("/api/feeAndLimit", feeAndLimits);
  app.use("/api/manualPayout", manualPayouts);
  app.use("/api/serviceArea", serviceAreas);
  app.use("/api/vehicleType", vehicleTypes);
  app.use("/api/pickUpCategory", pickUpCategories);
  app.use("/api/paymentHistory", paymentHistories);
  app.use("/api/role", roles);
  app.use("/api/analysis", analysis);
  app.use("/api/bank", banks);
  app.use("/api/csvUpload", csvUpload);

};
